/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VitasyncRouteImport } from './routes/vitasync'
import { Route as TestRouteImport } from './routes/test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as SkillIndexRouteImport } from './routes/skill/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as SkillCreateRouteImport } from './routes/skill/create'
import { Route as SkillIdRouteImport } from './routes/skill/$id'
import { Route as ChatIdRouteImport } from './routes/chat/$id'
import { Route as AgentCreateRouteImport } from './routes/agent/create'
import { Route as AgentIdRouteImport } from './routes/agent/$id'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLogoutRouteImport } from './routes/(auth)/logout'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authAccountRouteImport } from './routes/(auth)/account'
import { Route as SkillIdEditRouteImport } from './routes/skill/$id.edit'
import { Route as AgentIdEditRouteImport } from './routes/agent/$id.edit'

const VitasyncRoute = VitasyncRouteImport.update({
  id: '/vitasync',
  path: '/vitasync',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillIndexRoute = SkillIndexRouteImport.update({
  id: '/skill/',
  path: '/skill/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillCreateRoute = SkillCreateRouteImport.update({
  id: '/skill/create',
  path: '/skill/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillIdRoute = SkillIdRouteImport.update({
  id: '/skill/$id',
  path: '/skill/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCreateRoute = AgentCreateRouteImport.update({
  id: '/agent/create',
  path: '/agent/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIdRoute = AgentIdRouteImport.update({
  id: '/agent/$id',
  path: '/agent/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLogoutRoute = authLogoutRouteImport.update({
  id: '/(auth)/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authAccountRoute = authAccountRouteImport.update({
  id: '/(auth)/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillIdEditRoute = SkillIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SkillIdRoute,
} as any)
const AgentIdEditRoute = AgentIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AgentIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/vitasync': typeof VitasyncRoute
  '/account': typeof authAccountRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/register': typeof authRegisterRoute
  '/agent/$id': typeof AgentIdRouteWithChildren
  '/agent/create': typeof AgentCreateRoute
  '/chat/$id': typeof ChatIdRoute
  '/skill/$id': typeof SkillIdRouteWithChildren
  '/skill/create': typeof SkillCreateRoute
  '/agent/': typeof AgentIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/skill/': typeof SkillIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/agent/$id/edit': typeof AgentIdEditRoute
  '/skill/$id/edit': typeof SkillIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/vitasync': typeof VitasyncRoute
  '/account': typeof authAccountRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/register': typeof authRegisterRoute
  '/agent/$id': typeof AgentIdRouteWithChildren
  '/agent/create': typeof AgentCreateRoute
  '/chat/$id': typeof ChatIdRoute
  '/skill/$id': typeof SkillIdRouteWithChildren
  '/skill/create': typeof SkillCreateRoute
  '/agent': typeof AgentIndexRoute
  '/chat': typeof ChatIndexRoute
  '/skill': typeof SkillIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/agent/$id/edit': typeof AgentIdEditRoute
  '/skill/$id/edit': typeof SkillIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/vitasync': typeof VitasyncRoute
  '/(auth)/account': typeof authAccountRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/logout': typeof authLogoutRoute
  '/(auth)/register': typeof authRegisterRoute
  '/agent/$id': typeof AgentIdRouteWithChildren
  '/agent/create': typeof AgentCreateRoute
  '/chat/$id': typeof ChatIdRoute
  '/skill/$id': typeof SkillIdRouteWithChildren
  '/skill/create': typeof SkillCreateRoute
  '/agent/': typeof AgentIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/skill/': typeof SkillIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/agent/$id/edit': typeof AgentIdEditRoute
  '/skill/$id/edit': typeof SkillIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/vitasync'
    | '/account'
    | '/login'
    | '/logout'
    | '/register'
    | '/agent/$id'
    | '/agent/create'
    | '/chat/$id'
    | '/skill/$id'
    | '/skill/create'
    | '/agent/'
    | '/chat/'
    | '/skill/'
    | '/tools/'
    | '/agent/$id/edit'
    | '/skill/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/vitasync'
    | '/account'
    | '/login'
    | '/logout'
    | '/register'
    | '/agent/$id'
    | '/agent/create'
    | '/chat/$id'
    | '/skill/$id'
    | '/skill/create'
    | '/agent'
    | '/chat'
    | '/skill'
    | '/tools'
    | '/agent/$id/edit'
    | '/skill/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/vitasync'
    | '/(auth)/account'
    | '/(auth)/login'
    | '/(auth)/logout'
    | '/(auth)/register'
    | '/agent/$id'
    | '/agent/create'
    | '/chat/$id'
    | '/skill/$id'
    | '/skill/create'
    | '/agent/'
    | '/chat/'
    | '/skill/'
    | '/tools/'
    | '/agent/$id/edit'
    | '/skill/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRoute: typeof TestRoute
  VitasyncRoute: typeof VitasyncRoute
  authAccountRoute: typeof authAccountRoute
  authLoginRoute: typeof authLoginRoute
  authLogoutRoute: typeof authLogoutRoute
  authRegisterRoute: typeof authRegisterRoute
  AgentIdRoute: typeof AgentIdRouteWithChildren
  AgentCreateRoute: typeof AgentCreateRoute
  ChatIdRoute: typeof ChatIdRoute
  SkillIdRoute: typeof SkillIdRouteWithChildren
  SkillCreateRoute: typeof SkillCreateRoute
  AgentIndexRoute: typeof AgentIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  SkillIndexRoute: typeof SkillIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vitasync': {
      id: '/vitasync'
      path: '/vitasync'
      fullPath: '/vitasync'
      preLoaderRoute: typeof VitasyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/': {
      id: '/skill/'
      path: '/skill'
      fullPath: '/skill/'
      preLoaderRoute: typeof SkillIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/create': {
      id: '/skill/create'
      path: '/skill/create'
      fullPath: '/skill/create'
      preLoaderRoute: typeof SkillCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/$id': {
      id: '/skill/$id'
      path: '/skill/$id'
      fullPath: '/skill/$id'
      preLoaderRoute: typeof SkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/create': {
      id: '/agent/create'
      path: '/agent/create'
      fullPath: '/agent/create'
      preLoaderRoute: typeof AgentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$id': {
      id: '/agent/$id'
      path: '/agent/$id'
      fullPath: '/agent/$id'
      preLoaderRoute: typeof AgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/logout': {
      id: '/(auth)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof authLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/account': {
      id: '/(auth)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof authAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/$id/edit': {
      id: '/skill/$id/edit'
      path: '/edit'
      fullPath: '/skill/$id/edit'
      preLoaderRoute: typeof SkillIdEditRouteImport
      parentRoute: typeof SkillIdRoute
    }
    '/agent/$id/edit': {
      id: '/agent/$id/edit'
      path: '/edit'
      fullPath: '/agent/$id/edit'
      preLoaderRoute: typeof AgentIdEditRouteImport
      parentRoute: typeof AgentIdRoute
    }
  }
}

interface AgentIdRouteChildren {
  AgentIdEditRoute: typeof AgentIdEditRoute
}

const AgentIdRouteChildren: AgentIdRouteChildren = {
  AgentIdEditRoute: AgentIdEditRoute,
}

const AgentIdRouteWithChildren =
  AgentIdRoute._addFileChildren(AgentIdRouteChildren)

interface SkillIdRouteChildren {
  SkillIdEditRoute: typeof SkillIdEditRoute
}

const SkillIdRouteChildren: SkillIdRouteChildren = {
  SkillIdEditRoute: SkillIdEditRoute,
}

const SkillIdRouteWithChildren =
  SkillIdRoute._addFileChildren(SkillIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRoute: TestRoute,
  VitasyncRoute: VitasyncRoute,
  authAccountRoute: authAccountRoute,
  authLoginRoute: authLoginRoute,
  authLogoutRoute: authLogoutRoute,
  authRegisterRoute: authRegisterRoute,
  AgentIdRoute: AgentIdRouteWithChildren,
  AgentCreateRoute: AgentCreateRoute,
  ChatIdRoute: ChatIdRoute,
  SkillIdRoute: SkillIdRouteWithChildren,
  SkillCreateRoute: SkillCreateRoute,
  AgentIndexRoute: AgentIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  SkillIndexRoute: SkillIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
